name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write  # ⬅️ 關鍵：必須給這個權限才能上傳 SARIF
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck SCA Scan
        id: black-duck-sca-scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          BLACKDUCK_TRUST_CERT: true
          DETECT_ACCURACY_REQUIRED: NONE
        with:
          ### SCANNING: Required fields
          blackducksca_scan_full: true
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          
 ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          blackducksca_reports_sarif_create: true # Create Black Duck SCA SARIF report and upload it as artifact
          # blackducksca_reports_sarif_file_path: '/Users/tmp/report.sarif.json' # File path including file name where SARIF report should be created(need to include file name as well)
          # blackducksca_reports_sarif_severities: 'CRITICAL,HIGH'
          # blackducksca_reports_sarif_groupSCAIssues: true # By default true
          blackducksca_upload_sarif_report: true  # Upload Black Duck SCA SARIF report in GitHub Advanced Security tab
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackducksca_upload_sarif_report is set as true


          ### Below configuration is used to enable automatic pull request comment based on Black Duck SCA scan result
          blackducksca_prComment_enabled: true
          # Mandatory when blackducksca_automation_prcomment is set to 'true'

          blackducksca_fixpr_enabled: true
