name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck SCA Scan
        id: black-duck-sca-scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          BLACKDUCK_TRUST_CERT: true       
          DETECT_ACCURACY_REQUIRED: NONE
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
         

          
